[project]
name = "tpoeitdh-fec-service"
version = "0.1.0"
description = "The price of eggs is too damn high - federal elections commission data service"
authors = [{ name = "ThatDevShparki", email = "shparki@thatdev.io" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic (>=2.10.6,<3.0.0)",
    "pydantic-settings (>=2.8.0,<3.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "flask (>=3.1.0,<4.0.0)",
    "sqlalchemy (>=2.0.38,<3.0.0)",
    "flask-sqlalchemy (>=3.1.1,<4.0.0)",
    "alembic (>=1.14.1,<2.0.0)",
    "structlog (>=25.1.0,<26.0.0)",
]

[tool.poetry]
packages = [{ include = "tpoeitdh_fec_service", from = "./src" }]

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.7"
pre-commit = "^4.1.0"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
coverage = "^7.6.12"
pytest-cov = "^6.0.0"
pytest-sugar = "^1.0.0"

[tool.black]
line-length = 80


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
